### ISSUE TITLE
tailwindcss 개발환경 세팅

### ISSUE THREAD

**Issue by shseok** [Chokoty/re-find_nextjs#132]
## Description
번들사이즈 개선 및 스타일 커스터마이징을 위해 ChakraUI에서 tailwindcss로 마이그레이션하고자 합니다.

## Why?
- 세부적인 반응형 디자인 및 상태  변화 스타일링(hover, focus)을 위해 ChakraUI를 사용했음에도, 기존 scss를 함께 사용했던 점과 달리 컴포넌트안에서 한 번에 작성가능합니다.
-  추가적인 css 파일은 필요가 없으며 오로지 className을 통하여 작성된 스타일링 코드는 적은 코드 줄수로 가독성을 높여줍니다.
- ChakraUI에서 제공한 컴포넌트들 중 외부 라이브러리를 쓴 컴포넌트(ex. Modal)를 사용하는데 스타일링 이슈가 존재합니다.
- ChakraUI의 몇몇 모듈(ex. chakra-ui/theme, framer-motion)은 너무나 큰 번들 사이즈를 차지하여 사용자의 페이지 경험에 영향을 미칠 수 있습니다.
## To-do
- [x] nextjs에 tailwindcss 세팅
- [x] 불필요한 **.module.scss 및 css파일 삭제
- [ ] ChakraUI에서 사용한 컴포넌트들을 커스터마이징하여 적용 후 기존 ChakraUI 컴포넌트 및 모듈 제거
- [ ] 다크모드 적용
- [ ] tailwindcss eslint 설정
- [ ] develop branch에서 최종 테스트 후 scss와 ChakraUI 관련 패키지 uninstall
## ETC
다소 많은 작업이 필요할 것으로 예상됩니다.
