### ISSUE TITLE
스타일 버그 수정 및 Font 최적화 

### ISSUE THREAD

**Issue by shseok** [Chokoty/re-find_nextjs#136]
## Description
1. 폰트: Next.js의 next/font를 사용하여 폰트를 최적화시키고자 합니다. 
2. 스타일: 작가페이지이동시 상단 nav바에 active style이 적용되지 않는 버그가 있습니다. 랜덤 가챠 이벤트 페이지에서 특집 팬아트 가챠의 경우 특정 버튼을 누를때마다 아래 버튼을 누르는 유도 문구를 초기화해야합니다.

## Why?
1. 폰트: 현재 .css file에서 font-face attribute로 cdn 통해 폰트를 다운로드 받아서 사용하고 있습니다. 하지만, 이경우 클라이언트에서 custom 폰트를 다운로드 받기 전까지는 Nextjs에서 사용 가능한 fallback font(Arial 등)를 사용하게 됩니다. custom 폰트 로드 전/로드 후에 폰트 사이즈 크기 차이로 인해 cumulative layout shift가 발생하여 사용자 경험을 크게 떨어뜨리게 됩니다. 따라서, Next.js의  next/font를 사용하여 font를 빌드 타임 때 한번만 다운로드 받고, fallback font가 사용되는 동안 css size-adjust 프로퍼티를 적용시켜서 글자 크기를 동일하게하여 layout shift가 발생하는 것을 막아줄 수 있습니다.

## To-do
- [ ] Next.js의 next/font를 사용하기
- [ ] 상단 nav바 스타일 버그 수정하기
- [ ] 특집 가챠 로딩 초기화 작업하기

### 다크모드 깜박임 버그
- 다크모드상태에서 새로고침시 발생
![녹화_2024_05_07_19_27_20_955](https://github.com/Chokoty/re-find_nextjs/assets/80726955/f625f19c-3add-48f7-8834-c537ce66f4ff)

## ETC
