### ISSUE TITLE
작품 상세 및 갤러리 상단 UI 수정 / 왁티홀 서비스 재개

### ISSUE THREAD

**Issue by shseok** [Chokoty/re-find_nextjs#140]
## Description

1. 작품 상세 페이지를 모달이 아닌 전체 페이지로 보여줄 수 있도록 변경합니다. 
2. 갤러리 페이지의 상단 이미지 위에 있는 글들을 화면 비율이 줄어들어도 일정함을 유지할 수 있도록 수정합니다.(feat. 라프텔)
3. 만우절에 오픈하여 현재는 중지된 왁티홀 서비스를 재개합니다.

## To-do
- [x] 현재 Intercepting Routes로 모달로 표시되는 작품 상세 페이지의 파일구조를 제거합니다.
    - 결국 작품상세페이지는 기존의 페이지형태로 전체화면으로 표시됩니다.
- [x] 갤러리 페이지의 상단 이미지 위에 글의 스타일링 구조를 수정합니다.
- [x] 왁티홀 서비스 재개를 위해 미들웨어에 이전 페이지로 리다이렉트하는 코드를 제거해줍니다.
