### ISSUE TITLE
맨 위로 이동 버튼 추가

### ISSUE THREAD

**Issue by shseok** [Chokoty/re-find_nextjs#143]
## Description

갤러리 & 작가 & 검색 페이지에 "맨 위로 돌아가기" 버튼을 구현하여 
광범위한 스크롤 후 페이지 상단으로 쉽게 이동할 수 있도록 함으로써 **사용자 경험을 향상**시킵니다.

## To-do
- [ ] 눈에 띄기 쉬워야하지만 방해가 되어서는 안되므로 위쪽 화살표가 있는 작은 원형 아이콘을 만들어야 합니다.
- [ ] 사용자가 특정 거리(ex. 300px) 아래로 스크롤한 후에만 버튼이 나타나야 합니다.
- [ ] 표준적이고 사용자 친화적인 위치인 페이지 오른쪽 하단에 버튼을 배치해야 합니다.
- [ ] 키보드 및 스크린 리더를 통해 버튼에 액세스할 수 있어야 합니다.
