### ISSUE TITLE
작가 & 검색 리스트 카드 컴포넌트에 Fade-In Animation 적용

### ISSUE THREAD

**Issue by shseok** [Chokoty/re-find_nextjs#144]
## Description

작가 & 검색 리스트에서 사용되는 카드 컴포넌트에 fade-in animation을 적용하여 시각젹 효과를 주어 사용자 경험을 향상시킵니다. 애니메이션은 서버에서 데이터를 받은 후 각 카드가 순차적으로 렌더링될 때 트리거되어야 합니다. 이렇게 하면 해당 카드가 차례로 렌더링되고 표시될 때 더 부드럽게 표현됩니다.

## To-do

- [ ] 페이드인 애니메이션은 작가 & 검색 목록 카드 컴포넌트에 적용됩니다.
- [ ] 각 카드는 서버에서 데이터를 받은 후 순차적으로 fade-in 합니다.
- [ ] 무한 스크롤에 구현될 것이므로 페이지별 가져올 개수와 각 카드 컴포넌트의 해당 index를 이용합니다. 
    - ``index % ROWS_PER_PAGE``: 스크롤할 때마다 0 ~ (한 번 스크롤당 일정량 - 1) 반복

## ETC

[Tailwindcss Transition Delay](https://tailwindcss.com/docs/transition-delay)
