### ISSUE TITLE
주르르님 생일 팬아트 전용 갤러리 추가

### ISSUE THREAD

**Issue by shseok** [Chokoty/re-find_nextjs#146]
## Description

당일 주르르님 생일로 인해 생일 축하 팬아트가 많이 생성되어 전용 갤러리를 만들고자 합니다.

## To-do

- [x] detailedGallery에 jururuBirthday 전용 쿼리 추가하기
- [x] 공지사항 로그 업데이트
- [x] 배너 슬라이드에 링크 버튼 추가
