### ISSUE TITLE
리파인드 웹 앱 바로가기 기능 추가

### ISSUE THREAD

**Issue by shseok** [Chokoty/re-find_nextjs#148]
## Description
사용자가 웹 사이트에 접근하려면 브라우저를 켜서 주소창에 긴 웹 사이트 주소를 입력해서 들어와야 합니다. 
기존에 방문한 링크의 경우에는 주소의 일부를 입력하면 자동 완성이 돼서 접근하기 조금 더 쉽겠지만 여전히 번거롭게 느껴지긴 합니다.  더불어, 우리 앱의 경우 타 앱과 이름이 겹쳐 구글 검색시 SEO 경쟁에 밀려 일반 검색으로 접근하기 힘듭니다.
웹 앱이 네이티브 앱처럼 홈 화면에서 접근 가능하다면 번거로움이 줄어 사용자의 방문 횟수 증가를 기대할 수 있습니다.

## To-do
- [x] 3가지 사전 조건 충족하기
    - HTTPS로 서비스 제공
    - 웹 앱 매니페스트 파일 제공
    - 서비스 워커 등록하기
- [x] 앱 설치 전용 모달 추가하기
- [x] 모바일 넓이 + 홈 화면 + 초기 1회 접속시 앱 설치 전용 모달 보여주기
- [x] 좀 더 페이지에서 다운로드 버튼 추가하여 앱 설치 전용 모달 열 수 있게하기
- [x] 수동 앱 설치 가이드 추가하기

## ETC
실제 모달을 통해 앱설치가 진행되는 작업은 Android 에서만 해당됩니다.
IOS 환경에서는 앱 설치 전용 모달에서 수동 앱 설치를 유도합니다.
