### ISSUE TITLE
검색 필터 관련 버그

### ISSUE THREAD

**Issue by shseok** [Chokoty/re-find_nextjs#160]
추후작성
## Description

기능에 어떤 버그가 있는지 알려주세요.

## Why?

원래 의도한 동작은 무엇이며 왜 발생했는지 설명해주세요.

## To-do

- [ ] 필터 UI 데이터 바인딩 시키기 (현재는 필터는 적용이 되지만 UI상 어떤걸 선택했는지 표기 x)
- [ ] 필터 세부 기간 선택시 에러 해결하기
- [ ] vlc 값 입력시 체크박스 활성화시키기
- [ ] 메인에서 키워드 적은 상태로 필터 걸고 검색 버튼 누를때 키워드가 사라지는 문제 고치기

## ScreenShot

버그에 대한 스크린샷을 남겨주세요.

## ETC

추가사항이 있다면 남겨주세요.
