### ISSUE TITLE
Refactor: 성능 개선

### ISSUE THREAD

**Issue by shseok** [Chokoty/re-find_nextjs#82]
## Description
LCP / Bundle Size를 개선하여 사용자 경험을 향상시키고자 합니다.

## To-do
- [ ] bundle size를 분석하고 최대한 줄여서 초기 로드 자바스크립트 크기를 줄이고자 합니다.
    - 특정 모듈을 dynamic import를 하여 번들 크기를 줄입니다.
- [ ] static image의 크기를 줄이고 next/image를 사용하여 lcp를 개선합니다.
- [ ] 중복되는 특정 api 호출을 개선합니다.

## ETC
- 개발 상황에 따라 서버 api를 환경변수로 분리할 필요가 있습니다.
