### ISSUE TITLE
Migration: Nextjs App Router로 전환

### ISSUE THREAD

**Issue by shseok** [Chokoty/re-find_nextjs#83]
## Description
번들사이즈 개선 및 기타 개발 편의성을 위해 App Router로 전환하고자 합니다.

## To-do
- [x] package 버전을 맞추고 경량화
- [x] next/router -> next/navigation
- [x] pages directory -> app directory

## ETC
- 오류 발견 및 처리를 위해 추후 eslint를 변경해서 type을 모두 정의해야합니다.
- 안쓰이는 코드를 정리해야합니다.
