### ISSUE TITLE
검색 기능 출시

### ISSUE THREAD

**Issue by shseok** [Chokoty/re-find_nextjs#92]
## Description
유저는 키워드 검색을 통해 일치하는 검색 결과를 확인할 수 있다. (텍스트 매칭) 
또한, 검색 필터를 적용하여 세부적인 검색이 가능하다.

## To-do
- [x] 검색어를 입력하여 검색 페이지에서 검색어에 대한 결과를 노출한다.
![github1](https://github.com/Chokoty/re-find_nextjs/assets/80726955/550cc550-7fd8-45c3-89ff-cf77c15293b8)
- [x] UX를 위해 최근 검색 기록을 추가한다.
- [x] 검색 페이지에서 유저는 필터를 통해 원하는 결과를 얻을 수 있다.
- [x] 필터에는 기간 / 카테고리 + 말머리 / 제목 or 본문 or 작가 포함 / 정렬(최신순,댓글순,좋아요순,조회수,업로드날짜순)/좋아요, 조회수,댓글수를 선택하여 검색을 허용한다.
- [x] 검색 결과는 UX를 고려하여 infnite scroll을 적용한다.

## ETC
- 모바일 화면에도 대응한다
- 추후 자연어, 태그 검색 기능을 도입한다
